name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python = 3.9
  - r-base = 4.1
  - r-dplyr
  - r-tidyverse
  - r-ggplot2
  - r-reshape2
  - r-plotly
  - r-stringr
  - r-rlang
  - r-lattice
  - r-caret
  - r-ellipse
  - r-kernlab
  - r-randomForest
  - pip
  - pip:
     - numpy
     - pandas
     - matplotlib
     - threadpoolctl
     - scipy
     - joblib
     - scikit-learn
     
   
     
